#include <user/sys/syscalls.h>

void GET_PARTITION_STATUS(PARTITION_STATUS_TYPE *PARTITION_STATUS,
                          RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_partition_status(PARTITION_STATUS);
}

void SET_PARTITION_MODE(OPERATING_MODE_TYPE OPERATING_MODE, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_set_partition_mode(OPERATING_MODE);
}

void GET_PROCESS_ID(PROCESS_NAME_TYPE PROCESS_NAME, PROCESS_ID_TYPE *PROCESS_ID,
                    RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_process_id(PROCESS_NAME, PROCESS_ID);
}

void GET_PROCESS_STATUS(PROCESS_ID_TYPE PROCESS_ID, PROCESS_STATUS_TYPE *PROCESS_STATUS,
                        RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_process_status(PROCESS_ID, PROCESS_STATUS);
}

void CREATE_PROCESS(PROCESS_ATTRIBUTE_TYPE *ATTRIBUTES, PROCESS_ID_TYPE *PROCESS_ID,
                    RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_create_process(ATTRIBUTES, PROCESS_ID);
}

void SET_PRIORITY(PROCESS_ID_TYPE PROCESS_ID, PRIORITY_TYPE PRIORITY,
                  RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_set_priority(PROCESS_ID, PRIORITY);
}

void SUSPEND_SELF(SYSTEM_TIME_TYPE TIME_OUT, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_suspend_self(TIME_OUT);
}

void SUSPEND(PROCESS_ID_TYPE PROCESS_ID, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_suspend(PROCESS_ID);
}

void RESUME(PROCESS_ID_TYPE PROCESS_ID, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_resume(PROCESS_ID);
}

void STOP_SELF(void) {
  sys_stop_self();
}

void STOP(PROCESS_ID_TYPE PROCESS_ID, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_stop(PROCESS_ID);
}

void START(PROCESS_ID_TYPE PROCESS_ID, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_start(PROCESS_ID);
}

void DELAYED_START(PROCESS_ID_TYPE PROCESS_ID, SYSTEM_TIME_TYPE DELAY_TIME,
                   RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_delayed_start(PROCESS_ID, DELAY_TIME);
}

void LOCK_PREEMPTION(LOCK_LEVEL_TYPE *LOCK_LEVEL, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_lock_preemption(LOCK_LEVEL);
}

void UNLOCK_PREEMPTION(LOCK_LEVEL_TYPE *LOCK_LEVEL, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_unlock_preemption(LOCK_LEVEL);
}

void GET_MY_ID(PROCESS_ID_TYPE *PROCESS_ID, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_my_id(PROCESS_ID);
}

void INITIALIZE_PROCESS_CORE_AFFINITY(PROCESS_ID_TYPE PROCESS_ID,
                                      PROCESSOR_CORE_ID_TYPE PROCESSOR_CORE_ID,
                                      RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_initialize_process_core_affinity(PROCESS_ID, PROCESSOR_CORE_ID);
}

void GET_MY_PROCESSOR_CORE_ID(PROCESSOR_CORE_ID_TYPE *PROCESSOR_CORE_ID,
                              RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_my_processor_core_id(PROCESSOR_CORE_ID);
}

void GET_MY_INDEX(PROCESS_INDEX_TYPE *PROCESS_INDEX, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_my_index(PROCESS_INDEX);
}

void TIMED_WAIT(SYSTEM_TIME_TYPE DELAY_TIME, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_timed_wait(DELAY_TIME);
}

void PERIODIC_WAIT(RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_periodic_wait();
}

void GET_TIME(SYSTEM_TIME_TYPE *SYSTEM_TIME, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_get_time(SYSTEM_TIME);
}

void REPLENISH(SYSTEM_TIME_TYPE BUDGET_TIME, RETURN_CODE_TYPE *RETURN_CODE) {
  *RETURN_CODE = sys_replenish(BUDGET_TIME);
}
